name: Tested, works

on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Submodule
        run: git submodule update --init --recursive

      - name: Install Packages (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install -y mingw

      - name: Install Packages (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get -y install catch2 g++-mingw-w64

      - name: Try Compile Debug
        run: make -j

      - name: Run Tests (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: make -j test

      - name: Try Cross Compile for Windows (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: make -j win
